name: Deploy ASP.NET Core API to IIS

on:
  push:
    branches:
      - main  # Triển khai khi có push lên nhánh chính

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    # 1. Checkout mã nguồn
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Cài đặt .NET SDK (nếu cần thiết)
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # Cập nhật version theo project của bạn

    # 3. Khôi phục các package cần thiết
    - name: Restore dependencies
      run: dotnet restore

    # 4. Build ứng dụng
    - name: Build API
      run: dotnet publish -c Release -o out

    # 5. Triển khai lên IIS
    - name: Deploy to IIS
      run: |
        # Thư mục đích trên IIS server (Cập nhật đường dẫn này)
        $iisPath = "C:\inetpub\wwwroot\MyAspNetApi"
        $sourcePath = "$(pwd)\out"

        # Kiểm tra và xóa thư mục cũ nếu cần
        if (Test-Path $iisPath) {
          Remove-Item -Recurse -Force -Path $iisPath
        }

        # Tạo lại thư mục đích
        New-Item -ItemType Directory -Path $iisPath

        # Sao chép file lên IIS
        Copy-Item -Path "$sourcePath\*" -Destination $iisPath -Recurse

        Write-Host "Deployment completed successfully."
