name: Deploy .NET Core to IIS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy to IIS
        run: |
          iisreset /stop
          Copy-Item ./publish/* C:\Users\super-admin\IIS Resource\TestCICD -Recurse -Force
          iisreset /start
